name: clean_arc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.3
  get_it: ^7.6.0
  intl: ^0.18.1
  ionicons: ^0.1.2
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  floor_generator: ^1.4.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
